name: Update adlists

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build adlists
        run: ./scripts/update-adlists.sh

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes"
            exit 0
          fi

          TS_UTC="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add adlists/*.hosts
          git commit -m "chore(adlists): update hosts ${TS_UTC} [skip ci]"
          git push
